version: '3.8'

name: 'virtuaflix'

services:
  db:
    image: postgres
    container_name: virtuaflix_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: virtuaflix
    ports:
      - 5432:5432
    volumes:
      - .pg_data:/var/lib/postgresql/data

volumes:
  .pg_data: